// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IIncrementSystem {
  function increment() external returns (uint32);

  function increment(uint32 amount) external returns (uint32 newValue);

  function getCounter() external view returns (uint32);

  function getCounter(uint32 amount) external view returns (uint32);
}
